public class Constants {
    public static final String PRACTICE_UNIT_SALESFORCE = 'Salesforce';
    public static final String PRACTICE_UNIT_JAVA = 'Java';

    public static final string JOB_POSITION_LOCATION_USA = 'USA';
    public static final string JOB_POSITION_LOCATION_Ukraine = 'Ukraine';

    public static final String SALESFORCE_TITLE_PREFIX = 'SF - ';
    public static final String REVIEW_TASK_SUBJECT = 'Review high budget application ';
    public static final String SYSTEM_ADMINISTRATOR_PROFILE_NAME = 'System Administrator';
    public static final String INVALID_VISA_TERMS_ERROR_MESSAGE='Please specify your visa date information'; 
    public static final string CANDIDATE_VISA_LESS_THAN_YEAR_ERROR_MESSAGE='You can not apply for this job due to your US visa expiration date. ';
}
